export interface IAnime {
	anime_id: number,
	url: string,
	image_jpg: string,
	image_jpg_small: string,
	image_jpg_large: string,
	image_webp: string,
	image_webp_small: string,
	image_webp_large: string,
	type: string,
	source: string,
	episodes: number,
	status: string,
	aired_from: string,
	aired_to: string,
	duration: string,
	rating: string,
	score: string,
	scored_by: number,
	rank: number,
	popularity: number,
	title: string,
};